services:
  - type: web
    name: whocaller-api
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn whocaller.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.10"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
